export const villagers_api_mock = {
  cat06: {
    id: 48,
    'file-name': 'cat06',
    name: {
      'name-USen': 'Punchy',
      'name-EUen': 'Punchy',
      'name-EUde': 'Julian',
      'name-EUes': 'Félix',
      'name-USes': 'Félix',
      'name-EUfr': 'Cédric',
      'name-USfr': 'Cédric',
      'name-EUit': 'Felix',
      'name-EUnl': 'Punchy',
      'name-CNzh': '尔光',
      'name-TWzh': '爾光',
      'name-JPja': 'ビンタ',
      'name-KRko': '빙티',
      'name-EUru': 'Панчи',
    },
    personality: 'Lazy',
    'birthday-string': 'April 11th',
    birthday: '11/4',
    species: 'Cat',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Play',
    'catch-phrase': 'mrmpht',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/48',
    image_uri: 'https://acnhapi.com/v1/images/villagers/48',
    'bubble-color': '#ffffff',
    'text-color': '#848484',
    saying: "There's always more fish in the sea!",
    'catch-translations': {
      'catch-USen': 'mrmpht',
      'catch-EUen': 'mrmpht',
      'catch-EUde': 'mrmpft',
      'catch-EUes': 'arenque',
      'catch-USes': 'gruuuah',
      'catch-EUfr': 'blébléblé',
      'catch-USfr': 'mimine',
      'catch-EUit': 'maramao',
      'catch-EUnl': 'plof',
      'catch-CNzh': '晃晃',
      'catch-TWzh': '晃晃',
      'catch-JPja': 'だのら',
      'catch-KRko': '노라줘',
      'catch-EUru': 'отдыхаем',
    },
  },
  cbr10: {
    id: 74,
    'file-name': 'cbr10',
    name: {
      'name-USen': 'Cheri',
      'name-EUen': 'Cheri',
      'name-EUde': 'Claudia',
      'name-EUes': 'Cerecita',
      'name-USes': 'Cerecita',
      'name-EUfr': 'Rosalie',
      'name-USfr': 'Rosalie',
      'name-EUit': 'Bonbon',
      'name-EUnl': 'Cheri',
      'name-CNzh': '樱桃',
      'name-TWzh': '櫻桃',
      'name-JPja': 'アセロラ',
      'name-KRko': '아세로라',
      'name-EUru': 'Шери',
    },
    personality: 'Peppy',
    'birthday-string': 'March 17th',
    birthday: '17/3',
    species: 'Cub',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fashion',
    'catch-phrase': 'tralala',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/74',
    image_uri: 'https://acnhapi.com/v1/images/villagers/74',
    'bubble-color': '#db6161',
    'text-color': '#fffce9',
    saying: 'Good things come in small packages.',
    'catch-translations': {
      'catch-USen': 'tralala',
      'catch-EUen': 'tralala',
      'catch-EUde': 'tralala',
      'catch-EUes': 'tralará',
      'catch-USes': 'tralará',
      'catch-EUfr': 'tralala',
      'catch-USfr': 'tralala',
      'catch-EUit': 'trallalà',
      'catch-EUnl': 'tralala',
      'catch-CNzh': '开玩笑的',
      'catch-TWzh': '開玩笑的',
      'catch-JPja': 'なんてね',
      'catch-KRko': '어쩜이래',
      'catch-EUru': 'тра-ля-ля',
    },
  },
};

export const villagers_mock = [
  {
    birthday: '11/4',
    birthday_string: 'April 11th',
    gender: 'Male',
    icon: 'https://acnhapi.com/v1/icons/villagers/48',
    id: 48,
    image: 'https://acnhapi.com/v1/images/villagers/48',
    nameCN: '尔光',
    nameDE: 'Julian',
    nameEN: 'Punchy',
    nameES: 'Félix',
    personality: 'Lazy',
    species: 'Cat',
  },
  {
    birthday: '17/3',
    birthday_string: 'March 17th',
    gender: 'Female',
    icon: 'https://acnhapi.com/v1/icons/villagers/74',
    id: 74,
    image: 'https://acnhapi.com/v1/images/villagers/74',
    nameCN: '樱桃',
    nameDE: 'Claudia',
    nameEN: 'Cheri',
    nameES: 'Cerecita',
    personality: 'Peppy',
    species: 'Cub',
  },
];
