export const villagers = [
  {
    birthday: '11/4',
    birthday_string: 'April 11th',
    gender: 'Male',
    icon: '/.web-test-runner/assets/img/punchy.png',
    id: 48,
    image: '/.web-test-runner/assets/img/punchy.png',
    nameCN: '尔光',
    nameDE: 'Julian',
    nameEN: 'Punchy',
    nameES: 'Félix',
    personality: 'Lazy',
    species: 'Cat',
  },
  {
    birthday: '17/3',
    birthday_string: 'March 17th',
    gender: 'Female',
    icon: '/.web-test-runner/assets/img/cheri.png',
    id: 74,
    image: '/.web-test-runner/assets/img/cheri.png',
    nameCN: '樱桃',
    nameDE: 'Claudia',
    nameEN: 'Cheri',
    nameES: 'Cerecita',
    personality: 'Peppy',
    species: 'Cub',
  },
];

export const wishlist_mock = [
  {
    birthday: '17/3',
    birthday_string: 'March 17th',
    gender: 'Female',
    icon: '/.web-test-runner/assets/img/cheri.png',
    id: 74,
    image: '/.web-test-runner/assets/img/cheri.png',
    nameCN: '樱桃',
    nameDE: 'Claudia',
    nameEN: 'Cheri',
    nameES: 'Cerecita',
    personality: 'Peppy',
    species: 'Cub',
  },
  {
    birthday: '10/2',
    birthday_string: 'February 10th',
    gender: 'Male',
    icon: 'https://acnhapi.com/v1/icons/villagers/70',
    id: 70,
    image: 'https://acnhapi.com/v1/images/villagers/70',
    nameCN: '玩具熊',
    nameDE: 'Berry',
    nameEN: 'Stitches',
    nameES: 'Parches',
    personality: 'Lazy',
    species: 'Cub',
  },
];

export const my_villagers_mock = [
  {
    birthday: '11/4',
    birthday_string: 'April 11th',
    gender: 'Male',
    icon: '/.web-test-runner/assets/img/punchy.png',
    id: 48,
    image: '/.web-test-runner/assets/img/punchy.png',
    nameCN: '尔光',
    nameDE: 'Julian',
    nameEN: 'Punchy',
    nameES: 'Félix',
    personality: 'Lazy',
    species: 'Cat',
  },
  {
    birthday: '17/6',
    birthday_string: 'June 17th',
    gender: 'Female',
    icon: 'https://acnhapi.com/v1/icons/villagers/47',
    id: 47,
    image: 'https://acnhapi.com/v1/images/villagers/47',
    nameCN: '纯纯',
    nameDE: 'Tanja',
    nameEN: 'Tangy',
    nameES: 'Tricia',
    personality: 'Peppy',
    species: 'Cat',
  },
];
